### PR TITLE
Try to enable contrib classes on osx.

### PR DESCRIPTION
**Pull request by johannesring**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This fixes issue #17 on osx.

### CODE REVIEW

**Comment by johannesring** [comment]
@conda-forge-admin, please rerender

**Comment by johannesring** [comment]
Looks like the failed checks are only for Python 3.11 and not related to the change in this PR.

**Comment by keiyamamo** [comment]
Hi @ramtingh
This is quite important issue for us and would like to fix it as soon as possible. 
Is there any way we can help with this?
Best,
Kei

**Comment by ramtingh** [comment]
@conda-forge-admin, please rerender

**Comment by ramtingh** [comment]
Thanks for the help @johannesring and @keiyamamo . The issues with 3.11 should fix themselves when VTK/ITK versions are updated in #19 .

**Comment by keiyamamo** [comment]
@ramtingh  Thank you for your quick response! I really appreciate it.

**Pull request merged**
